name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Shell Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Setup development environment
        run: just setup

      - name: Lint shell scripts
        run: just lint

      - name: Test system functionality
        run: just test-bats

      - name: Validate system structure
        run: just validate

      - name: Test documentation format
        run: just docs

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Security scan
        run: just security

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run integration tests
        run: just integration

  validate-release:
    name: Validate Release Readiness
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Validate release readiness
        run: just release-check
